config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :admins, path: :admin
  devise_for :users

  namespace :admin do
    resources :forms, only: [:index, :create, :destroy]
    resources :lengths, only: [:index, :create, :destroy]
    resources :styles, only: [:index, :create, :destroy, :update]
  end

  resources :users, only: [:show, :create, :update, :destroy]
  resources :posts, only: [:index, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get "/style", to: "styles#show", as: "style"
  get "/styles", to: "styles#index", as: "styles"
  # resourcesでstyle書いてたらshowに:idが発行されてstyleの:id指定が必要になってしまった
  # sを外すとindexが生成されない為直書き
  root 'homes#top'
  get "home/about" => "homes#about"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  # post_idとuser_id の組が1組しかないようにする
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/form.rb
class Form < ApplicationRecord
  has_many :styles, dependent: :destroy
  attachment :form_image

  validates :form_name, presence: true
  validates :form_image, presence: true
end

app/models/length.rb
class Length < ApplicationRecord
  has_many :styles, dependent: :destroy
  attachment :length_image

  validates :length_name, presence: true
  validates :length_image, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    # favoritesのFKとして持ってるuser_idの中にuserのidが存在しているか
  end
  attachment :post_image
  validates :title, presence: true
  validates :post_body, presence: true
  validates :post_image, presence: true

  def self.search(search)
    if search
      Post.where(['title LIKE ? OR post_body LIKE ? OR winding LIKE ? OR item LIKE ? OR size LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
    end
  end
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :length
  belongs_to :form
  attachment :style_image

  validates :style_image, presence: true
  validates :style_body, presence: true
  validates :style_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :icon_image

  validates :name, presence: true
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :index, :update, :destroy]
  before_action :post_correct_user, only: [:destroy]
  before_action :correct_user, only: [:update]

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "create post."
      redirect_to posts_path
    else
      @posts = Post.all.order(id: "DESC")
      @favorite = Favorite.new
      @comment = Comment.new
      user_ids = Favorite.joins(:post).group("posts.user_id").order("count_all desc").limit(3).count.keys
      @ranks = User.where(id: user_ids).sort_by { |user| user_ids.index(user.id) }
      render "index"
    end
  end

  def index
    @posts = Post.all.order(id: "DESC")
    @post = Post.new
    @favorite = Favorite.new
    @comment = Comment.new
    user_ids = Favorite.joins(:post).group("posts.user_id").order("count_all desc").limit(3).count.keys
    # .joins=内部結合 結合しないものは削除する favoriteとpostが結びついた物をの中でpost.user_idでグループ分けレコード数をカウント 全て昇順に並べ表示数(3)
    # 配列=(keys(user_id),velue(いいね件数))のkeysのみを取得
    @ranks = User.where(id: user_ids).sort_by { |user| user_ids.index(user.id) }
    # whereによりid順に並び替えられてしまった為.sort_by(昇順に並び替える)を使用。
    # .indexで順番をふり並び替える

    # @rankings = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    # いいねランキング = post_idが同じものグループ分けしていいね数の昇順に 表示数 pluckでidを配列に 配列として取り出したidをfind
  end

  def update
    @update_post = Post.find(params[:id])
    if @update_post.update(post_params)
      flash[:notice] = "update post."
      redirect_to user_path(current_user)
    else
      @user = User.find(@update_post.user_id)
      @posts = @user.posts.order(id: "DESC")
      @comment = Comment.new
      @post = Post.new
      render "users/show"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:post_image, :title, :post_body, :winding, :item, :size, :user_id)
  end
  # def correct_user
  #     user = User.find(params[:id])
  #     if user.id != current_user.id
  #     redirect_to top_path
  #     end
  #    end
  # ↑のだとpostをupdate/destroyする際に(post)とするとpost.idのみでuser.idを定義できなくてエラーになった
  # その為↓の書き方をした params[:user_id]だけだと文字列になってしまうので.to_iで整数に

  def post_correct_user
    if params[:user_id].to_i != current_user.id
      redirect_to top_path
    end
  end

  def correct_user
    post = Post.find(params[:id])
    if post.user_id != current_user.id
      redirect_to top_path
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @posts = Post.search(params[:search]).order(id: "DESC")
    # viewのformで取得したパラメータをモデルに渡す
    @favorite = Favorite.new
    @comment = Comment.new
    @post = Post.new
    @search = params[:search]
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :authenticate_user!

  def show
    @style = Style.find_by(form_id: params[:form_id], length_id: params[:length_id])
                          # ↑ 外部キー        ↑form_tagで指定した名前
    # (params[:id])でfindする際は.find 指定する場合はfind_by
  end

  def index
    @forms = Form.all
    @lengths = Length.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :update]
  before_action :correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: "DESC")
    @comment = Comment.new
    @post = Post.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      @posts = @user.posts.order(id: "DESC")
      @comment = Comment.new
      @post = Post.new
      render user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :icon_image)
  end

  def correct_user
    user = User.find(params[:id])
    if user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/ueers_helper.rb
module UeersHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="media">
    <div class="col-xs-3">
      <%= attachment_image_tag @user, :icon_image, format: 'jpeg', fallback: "20161008_noimage 2 2.png",size:'100x100', id:"user_image",class:"img-circle"%>
    </div>
    <div class="col-xs-9">
      <div class="row" id="media_body">
        <div class="col-xs-7 ">
          <h3 class="media_name">
            <%= @user.name %>
          </h3>
        </div>
        <div class="col-xs-5 ">
          <% if @user.id == current_user.id %>
            <div class="alert-warning">
              <% unless @update_post.nil? %>
                <% if @update_post.errors.any? %>
                  <ul>
                    <% @update_post.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                <% end %>
              <% end %>
            </div>
            <div class="user_edit_modal">
              <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#userEditModal" data-backdrop="false">
                <span class="glyphicon glyphicon-cog"></span>
              </button>
              <div class="modal" id="userEditModal" role="dialog" >
                <div class="modal-dialog modal-dialog-centered" >
                  <div class="modal-content" id="edit_modal">
                    <%= form_for @user do |f| %>
                      <div class="modal-header">
                        <h1 class="modal-title">Edit User</h1>
                          <button type="button" class="close" data-dismiss="modal" >
                            <span class="glyphicon glyphicon-remove" ></span>
                          </button>
                      </div>
                      <div class="modal-body">
                        <div class="row">
                          <% if @user.errors.any? %>
                            <div class="alert-warning">
                              <ul>
                                <% @user.errors.full_messages.each do |message| %>
                                  <li><%= message %></li>
                                <% end %>
                              </ul>
                            </div>
                          <% end %>
                        </div>
                        <div class="row">
                          <div class="form-group">
                            <%= f.label "ニックネーム" %>
                            <%= f.text_field :name , rows:'1', class: "form-control"%>
                          </div>
                          <div class="form-group">
                            <%= f.attachment_field :icon_image, class: "image" %>
                              <% if @user.icon_image_id.present? %>
                                <%= attachment_image_tag @user, :icon_image, class: "img_prev" %>
                              <% else %>
                                <%= image_tag "20161008_noimage 2 2.png", class: "img_prev" %>
                              <% end %>
                          </div>
                        </div>
                      </div>
                      <div class="modal-footer">
                        <div class="form-group">
                          <%= f.submit 'Update' , class:"btn-default btn-lg btn " %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <table class="table">
    <tbody>
      <% @posts.each_slice(3) do |slice|  %>
        <tr>
          <% slice.each do |post| %>
            <td>
              <div class="user_post">
                <div class="row">
                  <% if post.user_id == current_user.id %>
                    <%= render 'posts/edit', post: post %>
                  <% end %>
                  <div class="user">
                    <button type="button" data-toggle="modal" data-target="#postModal<%= post.id %>" data-backdrop="false" id="post_image">
                      <%= attachment_image_tag post, :post_image, :fill, 300, 300, format: 'jpeg', fallback: "20161008_noimage 2 2.png", size:'300x300',id:"post_image" %>
                      <p class="far fa-thumbs-up"><%= post.favorites.count %></p>
                      <i class="far fa-comment fa-2x"><%= post.comments.count %></i>
                    </button>
                    <div class="modal" id="postModal<%= post.id %>" role="dialog" >
                      <div class="modal-dialog modal-dialog-centered" >
                        <div class="modal-content" id="post_modal">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" >
                              <span class="glyphicon glyphicon-remove" ></span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <div class="user_post">
                              <div class="row">
                                <div class="modal_image">
                                  <%= attachment_image_tag post, :post_image, :fill, 500, 500, format: 'jpeg', fallback: "20161008_noimage 2 2.png", size:'500x500' %>
                                </div>
                              </div>
                              <div class="row">
                                <div id="favorite_btn-<%= post.id %>">
                                  <%= render 'favorites/favorite', post: post %>
                                </div>
                              </div>
                              <div class="post_collapse">
                                <%= render 'posts/collapse', post: post %>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>