config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :admins, path: :admin
  devise_for :users

  namespace :admin do
    resources :forms, only: [:index, :create, :destroy]
    resources :lengths, only: [:index, :create, :destroy]
    resources :styles, only: [:index, :create, :destroy, :update]
  end

  resources :users, only: [:show, :create, :update, :destroy]
  resources :posts, only: [:index, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get "/style", to: "styles#show", as: "style"
  get "/styles", to: "styles#index", as: "styles"
  # resourcesでstyle書いてたらshowに:idが発行されてstyleの:id指定が必要になってしまった
  # sを外すとindexが生成されない為直書き
  root 'homes#top'
  get "home/about" => "homes#about"
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :length
  belongs_to :form
  attachment :style_image

  validates :style_image, presence: true
  validates :style_body, presence: true
  validates :style_name, presence: true
end

app/controllers/admin/styles_controller.rb
class Admin::StylesController < ApplicationController
  def index
    @styles = Style.all
    @style = Style.new
  end

  def create
    @style = Style.new(style_params)
    # binding.pry
    if @style.save
      flash[:notice] = "created style."
      redirect_to admin_styles_path
    else
      @styles = Style.all
      render admin_styles_path
    end
  end

  def destroy
    style = Style.find(params[:id])
    style.destroy
    redirect_to admin_styles_path
  end

  def update
    @style = Style.find(params[:id])
    @style.update!(style_params)
    redirect_to admin_styles_path
  end

  private

  def style_params
    params.require(:style).permit(:style_image, :style_body, :style_name, :length_id, :form_id)
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :authenticate_user!

  def show
    @style = Style.find_by(form_id: params[:form_id], length_id: params[:length_id])
                          # ↑ 外部キー        ↑form_tagで指定した名前
    # (params[:id])でfindする際は.find 指定する場合はfind_by
  end

  def index
    @forms = Form.all
    @lengths = Length.all
  end
end

app/helpers/admin/styles_helper.rb
module Admin::StylesHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/index.html.erb
<div class="form_group">
  <%= form_tag(style_path, method: :get) do %>
  <!-- 特にデータを保存せずに次のページに表示するだけだからgetを使う。postにするとデータが消えてしまう -->
    <div class="row">
      <div class="col-xs-7">
        <h1>あなたの顔型を選択</h1>
          <% @forms.each do |form| %>
            <div class="row">
              <div class="form-check">
                <%= radio_button_tag :form_id, form.id, false, class: "form-check-input", required: true %>
<!-- :form_idは名前の定義だからなんでも良い form.idは次のビューで必要な情報はidなので表記 オールチェックされた為false表記
検証で見ると→ <input type="radio" name="form_id" id="form_id" value="3" class="form-check-input"> -->
<!--                                                                ↑ idがちゃんと出てOK required: trueはエラー分-->
                <%= form.form_name %>
              </div>
              <div class="row">
                <div class="col-xs-4">
                  <%= attachment_image_tag form, :form_image, :fill, 150, 200, fallback: "20161008_noimage 2 2.png", size:'150x200' %>
                </div>
                <div class="col-xs-8">
                  <%= simple_format(form.form_body) %>
                  <!-- simple_formatを使うと入力した時の改行などがそのまま適用される -->
                </div>
              </div>
            </div>
          <% end %>
      </div>
      <div class="col-xs-1">
      </div>
      <div class="col-xs-4">
        <h1>髪の長さを選択</h1>
          <% @lengths.each do |length| %>
            <div class="row">
              <div class="form-check">
                <%= radio_button_tag :length_id, length.id, false, class:  "form-check-input", required: true %>
                <%= length.length_name %>
              </div>
            </div>
            <div class="row">
              <%= attachment_image_tag length, :length_image, :fill, 200, 200, fallback: "20161008_noimage 2 2.png", size:'210x210' %>
            </div>
          <% end %>
        <%= submit_tag "Search Start", class:"btn-default btn-lg btn ", id:"stylebut" %>
      </div>
    </div>
  <% end %>
</div>

app/views/styles/show.html.erb
<div class="row" id="style_show">
  <div class="col-xs-6">
    <%= attachment_image_tag @style, :style_image, fallback: "20161008_noimage 2 2.png", class:"style_image" %>
  </div>
  <div class="col-xs-6">
    <h1>Personal Style</h1>
    <div class="body">
      <span class="body_title">point</span>
      <%= simple_format(@style.style_body) %>
    </div>
    <div class="name">
      <%= simple_format(@style.style_name) %>
    </div>
    <i class="fas fa-hand-point-up"></i>検索してみんなの投稿で見てみよう<i class="fas fa-hand-point-up"></i>
  </div>
</div>